# -*- coding: utf-8 -*-
"""self pruning NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DhghQHMjTovXb3QvfabWFFLjXKsmK1w
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.01)
        self.bias = nn.Parameter(torch.zeros(out_features))
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features) * 0.01)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        return F.linear(x, self.weight * gates, self.bias)

class SelfPruningNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = PrunableLinear(32 * 32 * 3, 512)
        self.bn1 = nn.BatchNorm1d(512)
        self.fc2 = PrunableLinear(512, 256)
        self.bn2 = nn.BatchNorm1d(256)
        self.fc3 = PrunableLinear(256, 10)
        self.dropout = nn.Dropout(0.3)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = self.dropout(F.relu(self.bn1(self.fc1(x))))
        x = self.dropout(F.relu(self.bn2(self.fc2(x))))
        return self.fc3(x)

def sparsity_loss(model):
    loss = 0
    for layer in model.modules():
        if isinstance(layer, PrunableLinear):
            loss += torch.sum(torch.sigmoid(layer.gate_scores))
    return loss

def compute_sparsity(model, threshold=0.5):
    total = 0
    pruned = 0
    for layer in model.modules():
        if isinstance(layer, PrunableLinear):
            gates = torch.sigmoid(layer.gate_scores)
            total += gates.numel()
            pruned += (gates < threshold).sum().item()
    return 100 * pruned / total

def evaluate(model, loader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    return 100 * correct / total

def collect_gates(model):
    values = []
    for layer in model.modules():
        if isinstance(layer, PrunableLinear):
            gates = torch.sigmoid(layer.gate_scores).detach().cpu().numpy().flatten()
            values.extend(gates)
    return np.array(values)

transform_train = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32, padding=4),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))
])

trainset = torchvision.datasets.CIFAR10(root="./data", train=True, download=True, transform=transform_train)
testset = torchvision.datasets.CIFAR10(root="./data", train=False, download=True, transform=transform_test)

trainloader = DataLoader(trainset, batch_size=128, shuffle=True, num_workers=2)
testloader = DataLoader(testset, batch_size=128, shuffle=False, num_workers=2)

lambdas = [0.5, 1.5, 3.0]
epochs = 5
results = []
best_model = None
best_score = -1
best_gates = None
history = {}

for lam in lambdas:
    model = SelfPruningNet().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()
    acc_history = []

    for epoch in range(epochs):
        model.train()
        running_loss = 0

        for images, labels in trainloader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels) + lam * sparsity_loss(model) / 1_000_000
            loss.backward()
            optimizer.step()

            running_loss += loss.item()

        acc = evaluate(model, testloader)
        acc_history.append(acc)
        print(f"Lambda {lam} | Epoch {epoch+1}/{epochs} | Loss {running_loss:.4f} | Accuracy {acc:.2f}%")

    final_acc = evaluate(model, testloader)
    final_sparsity = compute_sparsity(model)
    results.append((lam, final_acc, final_sparsity))
    history[lam] = acc_history

    score = final_acc + 0.1 * final_sparsity
    if score > best_score:
        best_score = score
        best_model = model
        best_gates = collect_gates(model)

print("\nFinal Results")
print("Lambda\tAccuracy\tSparsity")
for lam, acc, sp in results:
    print(f"{lam}\t{acc:.2f}%\t\t{sp:.2f}%")

torch.save(best_model.state_dict(), "best_model.pth")

plt.figure(figsize=(6, 4))
plt.plot([r[2] for r in results], [r[1] for r in results], marker="o")
plt.xlabel("Sparsity (%)")
plt.ylabel("Accuracy (%)")
plt.title("Accuracy vs Sparsity Trade-off")
plt.grid(True)
plt.savefig("tradeoff_plot.png")
plt.show()

plt.figure(figsize=(6, 4))
for lam, acc_list in history.items():
    plt.plot(range(1, epochs + 1), acc_list, marker="o", label=f"lambda={lam}")
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Training Accuracy Curves")
plt.legend()
plt.grid(True)
plt.savefig("training_curves.png")
plt.show()

plt.figure(figsize=(6, 4))
plt.hist(best_gates, bins=50)
plt.xlabel("Gate Value")
plt.ylabel("Frequency")
plt.title("Gate Distribution of Best Model")
plt.grid(True)
plt.savefig("gate_distribution.png")
plt.show()

